package modelo;
// Generated 30/09/2016 14:45:49 by Hibernate Tools 5.1.0.Alpha1

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio implements java.io.Serializable {

	private int dni;
	private Persona persona;
	private String calle;
	private Integer altura;

	public Domicilio() {
	}

	public Domicilio(Persona persona) {
		this.persona = persona;
	}

	public Domicilio(Persona persona, String calle, Integer altura) {
		this.persona = persona;
		this.calle = calle;
		this.altura = altura;
	}

	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getAltura() {
		return this.altura;
	}

	public void setAltura(Integer altura) {
		this.altura = altura;
	}

}
