package modelo;
// Generated 30/09/2016 14:45:49 by Hibernate Tools 5.1.0.Alpha1

/**
 * Prueba generated by hbm2java
 */
public class Prueba implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Integer telefono;
	private Integer codigoPostal;

	public Prueba() {
	}

	public Prueba(int id) {
		this.id = id;
	}

	public Prueba(int id, Usuario usuario, Integer telefono, Integer codigoPostal) {
		this.id = id;
		this.usuario = usuario;
		this.telefono = telefono;
		this.codigoPostal = codigoPostal;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Integer getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(Integer codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

}
